---
kind: pipeline
name: default


steps:
  - name: sync_push
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/vtom-vertx.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - push
    commands:
      - git remote add github $REPO_REMOTE
      - git push github $DRONE_BRANCH

  - name: sync_tag
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/vtom-vertx.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - tag
    commands:
      - git remote add github $REPO_REMOTE
      - git fetch origin
      - git push github $DRONE_TAG

volumes:
  - name: git_credentials
    host:
      path: /data/mount/git/.git-credentials
  - name: git_config
    host:
      path: /data/mount/git/.gitconfig


---
kind: pipeline
name: deploy

steps:
  - name: pg_setup
    image: postgres:11-alpine
    environment:
      PGPASSWORD: passwd
    commands:
      - sleep 3
      - psql -U postgres -d vtom -h database -f /drone/src/vtom-test/src/test/resources/schema/vtom.sql

  - name: deploy
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
      - name: gpg
        path: /root/.gnupg
    environment:
      DB_URL: jdbc:postgresql://database:5432/vtom
      DB_USER: postgres
      DB_PASSWD: passwd
      REDIS_HOST: redis
    commands:
      - apk add gnupg
      - mvn clean deploy -Prelease

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: gpg
    host:
      path: /data/gnupg

services:
  - name: database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vtom
      POSTGRES_PASSWORD: passwd

  - name: redis
    image: redis:4-alpine

trigger:
  event:
    - tag

---
kind: pipeline
name: install

steps:
  - name: pg_setup
    image: postgres:11-alpine
    environment:
      PGPASSWORD: passwd
    commands:
      - sleep 3
      - psql -U postgres -d vtom -h database -f /drone/src/vtom-test/src/test/resources/schema/vtom.sql

  - name: install
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
    commands:
      - mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true

volumes:
  - name: m2
    host:
      path: /data/mount/m2

services:
  - name: database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vtom
      POSTGRES_PASSWORD: passwd

  - name: redis
    image: redis:4-alpine

trigger:
  event:
    - push



