---
kind: pipeline
name: default

---
kind: pipeline
name: maven_center

steps:
  - name: pg_setup
    image: postgres:11-alpine
    environment:
      PGPASSWORD: passwd
    commands:
      - sleep 3
      - psql -U postgres -d vtom -h database -f /drone/src/vtom-test/src/test/resources/schema/vtom.sql

  - name: deploy
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
      - name: gpg
        path: /root/.gnupg
    environment:
      DB_URL: jdbc:postgresql://database:5432/vtom
      DB_USER: postgres
      DB_PASSWD: passwd
      REDIS_HOST: redis
    commands:
      - apk add gnupg
      - mvn clean deploy -Prelease

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: gpg
    host:
      path: /data/gnupg

services:
  - name: database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vtom
      POSTGRES_PASSWORD: passwd

  - name: redis
    image: redis:4-alpine

trigger:
  branch:
    - master

---
kind: pipeline
name: install_local

steps:
  - name: install
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
    commands:
      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

volumes:
  - name: m2
    host:
      path: /data/mount/m2

trigger:
  branch:
    - dev



#---
#kind: pipeline
#name: install_local
#
#steps:
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2
#
#trigger:
#  branch:
#    - dev




#---
#kind: pipeline
#name: default
#
#steps:
#
#  ## xtodo deploy mode
#  - name: deploy
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean package -Dmaven.test.skip=true
#    when:
#      branch:
#        - master
#
#
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
#    when:
#      branch:
#        - dev
#
#
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2

