---
kind: pipeline
name: default

---
kind: pipeline
name: maven_center

steps:
  - name: deploy
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
      - name: gpg
        path: /root/.gnupg
    commands:
      - apk add gnupg
      - mvn clean deploy -Dmaven.test.skip=true -Prelease

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: gpg
    host:
      path: /data/gnupg

trigger:
  branch:
    - master

---
kind: pipeline
name: install_local

steps:
  - name: test
    image: postgres:11-alpine
    commands:
      - sleep 15
      - psql -U postgres -d vtom -h database
  - name: install
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
    environment:
      DB_URL: jdbc:postgresql://database:5432/vtom
      DB_USER: postgres
      DB_PASSWD: passwd
      REDIS_HOST: redis
    commands:
      - mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true #  -Dmaven.test.skip=true

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: sql
    host:
      path: /var/lib/mysql

services:
  - name: database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vtom
      POSTGRES_PASSWORD: passwd
    commands:
      - cp /drone/src/vtom-test/src/test/resources/schema/vtom.sql /docker-entrypoint-initdb.d/init.sql

trigger:
  branch:
    - dev



#---
#kind: pipeline
#name: install_local
#
#steps:
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2
#
#trigger:
#  branch:
#    - dev




#---
#kind: pipeline
#name: default
#
#steps:
#
#  ## xtodo deploy mode
#  - name: deploy
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean package -Dmaven.test.skip=true
#    when:
#      branch:
#        - master
#
#
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
#    when:
#      branch:
#        - dev
#
#
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2

