
---
kind: pipeline
name: default

---
kind: pipeline
name: maven_center

steps:
  - name: deploy
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
      - name: gpg
        path: /root/.gnupg
    commands:
      - apk add gnupg
      - mvn clean deploy -Dmaven.test.skip=true -Prelease

volumes:
  - name: m2
    host:
      path: /data/mount/m2
  - name: gpg
    host:
      path: /data/gnupg

trigger:
  branch:
    - master

---
kind: pipeline
name: install_local

steps:
  - name: install
    image: maven:3.6-alpine
    volumes:
      - name: m2
        path: /root/.m2
    commands:
      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

volumes:
  - name: m2
    host:
      path: /data/mount/m2

trigger:
  branch:
    - dev


#---
#kind: pipeline
#name: default
#
#steps:
#
#  ## xtodo deploy mode
#  - name: deploy
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean package -Dmaven.test.skip=true
#    when:
#      branch:
#        - master
#
#
#  - name: install
#    image: maven:3.6-alpine
#    volumes:
#      - name: m2
#        path: /root/.m2
#    commands:
#      - mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
#    when:
#      branch:
#        - dev
#
#
#
#volumes:
#  - name: m2
#    host:
#      path: /data/mount/m2

